services:
  web:
    build:
      context: ./cms-web
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - api
    networks:
      - app-network

  api:
    build:
      context: ./cms-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
