import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Sidebar from './components/sidebar/sidebar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Testimonios',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className={`${geistSans.variable} ${geistMono.variable} `}>
      <body className='h-screen overflow-hidden bg-linear-to-tr from-[#f8fafc] via-[#eef2f6] to-[#f8fafc]'>
        <div className='flex h-full'>
          <Sidebar />
          <main className='flex-1 overflow-y-auto'>{children}</main>
        </div>
      </body>
    </html>
  )
}
