name: Build
on:
  push:
    branches:
      - main
      - develop
      - 'dev*'
      - 'bac*'
      - 'fro*'
  pull_request:
    branches:
      - main
      - develop
      - 'dev*'
      - 'bac*'
      - 'fro*'
  workflow_dispatch:
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Write sonar-project.properties from secret
        run: |
          echo "${{ secrets.SONAR_PROPERTIES_FILE }}" > sonar-project.properties

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectKey: devcodenc2_frontend
          organization: devcodenc2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}